services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - app_network

  db:
    image: postgres:latest
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    ports:
      - 5432:5432
    container_name: postgres
    env_file:
      - secrets.env
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    driver: bridge