---
name: Docker Image CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build-test:
    name: Container Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d