name: Docker Compose Build and Run

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверить исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Шаг 3: Запустить docker-compose up --build
      - name: Run Docker Compose
        run: |
          docker-compose up --build -d